id: AC89CC92C
title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
type: translation
pechas:
- IB0E0C070
- IC8A674BD
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:08:50.055204
  last_modified_at: 2023-01-04 13:08:50.055209
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IB0E0C070/9F95: 6FFB
  IC8A674BD/256B: 6FFB
